version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/vcn"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/instances"
    schedule:
      interval: "weekly"
